---
title: "Homework 5"
author: "Sihan Qiu"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

set.seed(1)
```

## Q1
```{r}
bdays_sim = function(n){

bdays = sample(1:365, size = n, replace = TRUE)

duplicate = length(unique(bdays)) < n  #check repeated birthdays
return(duplicate)
}

bdays_sim(10)
```

```{r, error=TRUE}
sim_res =
  expand_grid(
    n = c(2, 50),
    iter = 1:10000
  )|>
  mutate(res = map_dbl(n,bdays_sim))|>
  group_by(n)|>
  summarize(prob = mean(res))

sim_res|>
  ggplot(aes(x = n, y = prob))+
  geom_line()
```


## Q2
```{r}
sim_mean_sd = function(n, mu = 0, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma)
  )
  sim_data |>
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
  
  test_result = 
    t.test(sim_data[["x"]], mu = 0)
  
  result = broom::tidy(test_result)
  
  tibble(
    mu_hat = mean(sim_data[["x"]]),
    sigma_hat = sd(sim_data[["x"]]),
    p_value = result[["p.value"]]
  )
}
```


```{r}
params = list(
  n = 30,
  sigma = 5,
  alpha = 0.05,
  mu_values = c(1, 2, 3, 4, 5, 6),
  num_simulations = 5000
)
```


```{r}
sim_results = map_df(params[["mu_values"]], function(mu)
{
  output= vector("list", 5000)
  
  for (i in 1:5000) {
  output[[i]] = sim_mean_sd(30)
  }
  bind_rows(output) |>
  mutate(true_mu = mu)
})
```



```{r}
power_results = 
  sim_results |>
  group_by(true_mu) |>
  summarize(
    power = mean(as.numeric(p_value) < params[["alpha"]]),                      
    avg_estimate = mean(mu_hat),                       
    avg_estimate_rejected = mean(mu_hat[as.numeric(p_value) < params[["alpha"]]])
  )

```


```{r}
ggplot(power_results, aes(x = true_mu, y = power)) +
  geom_line() +
  geom_point() +
  labs(x = "True Value of μ", y = "Power of the Test",
       title = "Power of the Test vs. True Value of μ")
```

```{r}
ggplot(power_results, aes(x = true_mu)) +
  geom_line(aes(y = avg_estimate), color = "blue", linetype = "solid") +
  geom_point(aes(y = avg_estimate), color = "blue") +
  geom_line(aes(y = avg_estimate_rejected), color = "red", linetype = "dashed") +
  geom_point(aes(y = avg_estimate_rejected), color = "red") +
  labs(x = "True Value of μ", y = "Average Estimate of μ̂",
       title = "Average μ̂ vs. True Value of μ",
       subtitle = "Blue: All Estimates, Red: Only Rejected Null Hypothesis") +
  theme_minimal()
```

## Q3
```{r}
homicide = read.csv("homicide-data.csv")|>
  janitor::clean_names()
```

### description of the raw dataset
the raw dataset includes `r nrow(homicide)` observations, and `r ncol(homicide)` variables. Key variables includes homicides' id, dates, victims' names, race, age, sex, state, city, and disposition of homicides, and the specific location. 

```{r}
homicide_clean = 
  homicide |>
  mutate(
    victim_last = str_to_title((victim_last)),
    victim_first = str_to_title((victim_first)),
    city_state = paste(city, state, sep = ", ")
  )|>
  drop_na()
```


```{r}
homicide_clean|>
  group_by(city_state) |>
  summarise(
    total = n(),
    unsolved = sum(disposition %in% c("Closed without arrest", "Open/No arrest"))
  )
```

## proportion of baltimore
```{r}
baltimore_df = 
  homicide_clean|>
  filter(city_state == "Baltimore, MD")
```

```{r}
total_bal = nrow(baltimore_df)
unsolved_bal = sum(pull(baltimore_df, disposition) %in% c("Closed without arrest", "Open/No arrest"))
```

```{r}
prop_test = prop.test(x = unsolved_bal, n = total_bal)
prop_test_df = broom::tidy(prop_test)
```


## proportion of each city
```{r}
city_prop_test = 
  homicide|>
  mutate(
    victim_last = str_to_title(victim_last),
    victim_first = str_to_title(victim_first),
    city_state = paste(city, state, sep = ", ")  # Create city_state by combining city and state
  ) |>
  drop_na() |>
  
  group_by(city_state) |>
  summarise(
    total_homicide = n(),
    unsolved_homicide = sum(disposition %in% c("Closed without arrest", "Open/No arrest"))
  ) |>
  mutate(
    prop_test = map2(unsolved_homicide, total_homicide, ~ prop.test(.x, .y)), 
    prop_test_tidy = map(prop_test, broom::tidy)  
  ) |>
  
  unnest(prop_test_tidy) |>
  
  select(city_state, total_homicide, unsolved_homicide, estimate, conf.low, conf.high) |>
  rename(
    estimated_proportion = estimate,
    conf_int_lower = conf.low,
    conf_int_upper = conf.high
  )

```


```{r}
city_prop_test =
  city_prop_test |>
  arrange(desc(estimated_proportion)) |>
  mutate(city_state = factor(city_state, levels = city_state)) 
```

## making a plot
```{r}
ggplot(city_prop_test, aes(x = city_state, y = estimated_proportion)) +
  geom_boxplot(aes(group = city_state), width = 0.6) +  
  geom_errorbar(aes(ymin = conf_int_lower, ymax = conf_int_upper), width = 0.3) +  
  labs(
    title = "Proportion of Unsolved Homicides by City",
    x = "City",
    y = "Estimated Proportion of Unsolved Homicides"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

